# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Shanghai"

[log]
    log_level = "trace"         #日志打印最低级别
    caller_skip = 3             #运行时文件查找级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./saber.inf.log"
        rotate_log_path = "./saber.inf.log"
        wf_log_path = "./saber.wf.log"
        rotate_wf_log_path = "./saber.wf.log"
    [log.console_writer]        #工作台输出
        on = true
        color = true